// // Generated by https://quicktype.io

// export interface MovieDBActorMostKnownTypes {
//     adult:                boolean;
//     also_known_as:        string[];
//     biography:            string;
//     birthday:             string;
//     deathday:             null;
//     gender:               number;
//     homepage:             null;
//     id:                   number;
//     imdb_id:              string;
//     known_for_department: string;
//     name:                 string;
//     place_of_birth:       string;
//     popularity:           number;
//     profile_path:         string;
// }

// Generated by https://quicktype.io

export interface MovieDBActorMostKnownTypes {
    id: number;
    original_language: string;
    poster_path: string;
    first_air_date: string;
    name: string;
    vote_count: number;
    original_name: string;
    origin_country: string[];
    vote_average: number;
    backdrop_path: string;
    overview: string;
    genre_ids: number[];
    popularity: number;
    character: string;
    credit_id: string;
    episode_count: number;
    media_type: string;
}
